WebBanHangOnline/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhSachYeuThiches = new HashSet<DanhSachYeuThich>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string SKU { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTaChiTiet { get; set; }
        public decimal GiaGoc { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string HinhAnhChinh { get; set; }
        public Nullable<bool> LaHangMoi { get; set; }
        public Nullable<bool> LaBanChay { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSanPham> AnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThiches { get; set; }
    }
}

WebBanHangOnline/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;

namespace WebBanHangOnline.Controllers
{
    public class SanPhamsController : Controller
    {
        private WebBanHangOnlineDBEntities db = new WebBanHangOnlineDBEntities();

        ///Login
        public ActionResult Login()
        {
            // Trả về View đăng nhập
            return View();
        }
        [HttpPost]

        public ActionResult Login(TaiKhoan tk)
        {
            var user = db.TaiKhoans.FirstOrDefault(u => u.Email == tk.Email && u.MatKhau == tk.MatKhau);
            if (user != null)
            {
                Session["User"] = user;
                return RedirectToAction("Index");
            }
            ViewBag.ErrorMessage = "Đăng nhập không thành công. Vui lòng kiểm tra lại thông tin.";
            return View();
        }


        public ActionResult CreateLogin()
        {
             return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLogin(TaiKhoan tk)
        {
            if (ModelState.IsValid)
            {
                db.TaiKhoans.Add(tk);
                db.SaveChanges();
                return RedirectToAction("Login");
            }
            return View(tk);
        }

        // GET: SanPhams
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.DanhMuc);
            return View(sanPhams.ToList());
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,TenSanPham,SKU,MoTaNgan,MoTaChiTiet,GiaGoc,GiaKhuyenMai,SoLuongTon,HinhAnhChinh,LaHangMoi,LaBanChay,MaDanhMuc")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,TenSanPham,SKU,MoTaNgan,MoTaChiTiet,GiaGoc,GiaKhuyenMai,SoLuongTon,HinhAnhChinh,LaHangMoi,LaBanChay,MaDanhMuc")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHangOnline/Views/SanPhams/Create.cshtml
@model WebBanHangOnline.Models.SanPham

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SKU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTaNgan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTaNgan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTaChiTiet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTaChiTiet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaGoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaGoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaKhuyenMai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaKhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaKhuyenMai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnhChinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnhChinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnhChinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaHangMoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LaHangMoi)
                    @Html.ValidationMessageFor(model => model.LaHangMoi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaBanChay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LaBanChay)
                    @Html.ValidationMessageFor(model => model.LaBanChay, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, "MaDanhMuc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebBanHangOnline/Views/SanPhams/CreateLogin.cshtml
@{
    ViewBag.Title = "Đăng Ký Tài Khoản";
    Layout = "~/Views/Shared/Login.cshtml"; 
}

<div class="container my-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Tạo Tài Khoản Mới</h3>
                </div>
                <div class="card-body">

                    <form method="post" action="/SanPhams/CreateLogin">

                        @Html.AntiForgeryToken()

                        @if (!ViewData.ModelState.IsValid)
                        {
                            <div class="alert alert-danger" role="alert">
                                Vui lòng kiểm tra lại các thông tin bạn đã nhập.
                            </div>
                        }


                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="inputHo" name="Ho" type="text" placeholder="Họ" required />
                                    <label for="inputHo">Họ</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="inputTen" name="Ten" type="text" placeholder="Tên" required />
                                    <label for="inputTen">Tên</label>
                                </div>
                            </div>
                        </div>

                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputEmail" name="Email" type="email" placeholder="Email" required />
                            <label for="inputEmail">Email</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputSoDienThoai" name="SoDienThoai" type="tel" placeholder="Số điện thoại" />
                            <label for="inputSoDienThoai">Số điện thoại</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputDiaChi" name="DiaChi" type="text" placeholder="Địa chỉ" />
                            <label for="inputDiaChi">Địa chỉ</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputPassword" name="MatKhau" type="password" placeholder="Mật khẩu" required />
                            <label for="inputPassword">Mật khẩu</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputConfirmPassword" name="ConfirmPassword" type="password" placeholder="Xác nhận mật khẩu" required />
                            <label for="inputConfirmPassword">Xác nhận mật khẩu</label>

                            @if (ViewBag.PasswordError != null)
                            {
                                <div class="text-danger small mt-1">
                                    @ViewBag.PasswordError
                                </div>
                            }
                        </div>

                        <div class="mt-4 mb-0">
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary btn-block rounded-pill py-3">Tạo Tài Khoản</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    <div class="small">
                        @Html.ActionLink("Đã có tài khoản? Đăng nhập ngay", "Login", "SanPhams")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebBanHangOnline/Views/SanPhams/Delete.cshtml
@model WebBanHangOnline.Models.SanPham

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaNgan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaNgan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaChiTiet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaChiTiet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaKhuyenMai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaKhuyenMai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnhChinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhChinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaHangMoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaHangMoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaBanChay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaBanChay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.TenDanhMuc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebBanHangOnline/Views/SanPhams/Details.cshtml
@model WebBanHangOnline.Models.SanPham

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaNgan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaNgan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaChiTiet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaChiTiet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaKhuyenMai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaKhuyenMai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnhChinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnhChinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaHangMoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaHangMoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaBanChay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaBanChay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.TenDanhMuc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaSanPham }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBanHangOnline/Views/SanPhams/Edit.cshtml
@model WebBanHangOnline.Models.SanPham

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSanPham)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SKU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTaNgan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTaNgan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTaChiTiet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTaChiTiet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaGoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaGoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaKhuyenMai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaKhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaKhuyenMai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnhChinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnhChinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnhChinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaHangMoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LaHangMoi)
                    @Html.ValidationMessageFor(model => model.LaHangMoi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaBanChay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LaBanChay)
                    @Html.ValidationMessageFor(model => model.LaBanChay, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, "MaDanhMuc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebBanHangOnline/Views/SanPhams/Login.cshtml
@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/Login.cshtml"; 
}

<div class="container my-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Đăng nhập</h3>
                </div>
                <div class="card-body">

                    <form method="post" action="/SanPhams/Login">
                        @Html.AntiForgeryToken()

                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputEmail" name="Email" type="email" placeholder="name@example.com" required />
                            <label for="inputEmail">Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input class="form-control" id="inputPassword" name="MatKhau" type="password" placeholder="Password" required />
                            <label for="inputPassword">Mật khẩu</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                            <a class="small" href="#">Quên mật khẩu?</a>
                            <button class="btn btn-primary rounded-pill py-2 px-4" type="submit">Đăng nhập</button>
                        </div>
                    </form>
                </div>

                <div class="card-footer text-center py-3">

                    @if (ViewBag.ErrorMessage != null)
                    {
                        <div class="small text-danger mb-2">
                            @ViewBag.ErrorMessage
                        </div>
                    }

                    <div class="small">
                        @Html.ActionLink("Chưa có tài khoản? Đăng ký ngay!", "CreateLogin", "SanPhams")
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>